[package]
name = "mixxx_libhelper"
version = "0.1.0"
authors = ["spotlesscoder <codingspiderfox@gmail.com>"]
edition = "2021"

[lib]
path ="./src/lib/lib.rs"

[dependencies]
gstreamer = "0.23.0"
id3 = "1.14.0"
regex = "1.10.5"
rusqlite = "0.31.0"
sha2 = "0.10.8"

