[package]
name = "mixxx_libhelper"
version = "0.1.0"
authors = ["spotlesscoder <codingspiderfox@gmail.com>"]
edition = "2021"

[lib]
path ="./src/lib/lib.rs"

[dependencies]
id3 = "1.14.0"
rusqlite = "0.31.0"

